### ISSUE TITLE
Why in proxy hi paste @ for  :  Help me pls) If start without proxy all okay

### ISSUE THREAD

**Issue by Karimadze** [BlackJkee/NotPixelBot#2]
![Снимок экрана 2024-09-26 161358](https://github.com/user-attachments/assets/3d6dd6b4-510b-4b4c-872a-b8f0e8340271)

**Comment by Karimadze** [comment]
I specified the proxy like this. 
"proxy": "socks5://AFR*****:JM****:45.66.****:5**"
"proxy": "type://user:pass:ip:port"

**Comment by BlackJkee** [comment]
Answered in the telegram channel.
